//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Components_Staking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Components_Staking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserLibrary.Resources.Components.Staking", typeof(Components_Staking).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加质押.
        /// </summary>
        internal static string Add_Staking {
            get {
                return ResourceManager.GetString("Add Staking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加 {0} LYR 到质押…….
        /// </summary>
        internal static string Add_staking_of__0__LYR___ {
            get {
                return ResourceManager.GetString("Add staking of {0} LYR...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加盈利账号…….
        /// </summary>
        internal static string Adding_profiting_account___ {
            get {
                return ResourceManager.GetString("Adding profiting account...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加质押账号…….
        /// </summary>
        internal static string Adding_staking_account___ {
            get {
                return ResourceManager.GetString("Adding staking account...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复利模式.
        /// </summary>
        internal static string Compound_Mode {
            get {
                return ResourceManager.GetString("Compound Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复利质押模式：.
        /// </summary>
        internal static string Compound_staking_mode_ {
            get {
                return ResourceManager.GetString("Compound staking mode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认！.
        /// </summary>
        internal static string Confirm_ {
            get {
                return ResourceManager.GetString("Confirm!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建盈利账号.
        /// </summary>
        internal static string Create_Profiting_Account {
            get {
                return ResourceManager.GetString("Create Profiting Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建质押.
        /// </summary>
        internal static string Create_Staking {
            get {
                return ResourceManager.GetString("Create Staking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建质押账号.
        /// </summary>
        internal static string Create_Staking_Account {
            get {
                return ResourceManager.GetString("Create Staking Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要质押的天数：.
        /// </summary>
        internal static string Days_of_staking_ {
            get {
                return ResourceManager.GetString("Days of staking:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误： {0}.
        /// </summary>
        internal static string Error___0_ {
            get {
                return ResourceManager.GetString("Error: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加质押失败。错误 {0}.
        /// </summary>
        internal static string Failed_adding_staking__Error___0_ {
            get {
                return ResourceManager.GetString("Failed adding staking. Error: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除质押失败。错误 {0}.
        /// </summary>
        internal static string Failed_to_unstake__Error___0_ {
            get {
                return ResourceManager.GetString("Failed to unstake. Error: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你想质押多少 LYR？.
        /// </summary>
        internal static string How_many_LYR_do_you_want_to_stake_ {
            get {
                return ResourceManager.GetString("How many LYR do you want to stake?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 店铺.
        /// </summary>
        internal static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称：.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节点.
        /// </summary>
        internal static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 什么都没改变。.
        /// </summary>
        internal static string Nothing_changed_ {
            get {
                return ResourceManager.GetString("Nothing changed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质押的数量 （0 - 100）.
        /// </summary>
        internal static string Number_of_staking__0___100__ {
            get {
                return ResourceManager.GetString("Number of staking (0 - 100):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预言机.
        /// </summary>
        internal static string Oracle {
            get {
                return ResourceManager.GetString("Oracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理中.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 盈利账号.
        /// </summary>
        internal static string Profiting_Account_ID {
            get {
                return ResourceManager.GetString("Profiting Account ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有盈利账号.
        /// </summary>
        internal static string Profiting_Accounts {
            get {
                return ResourceManager.GetString("Profiting Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比例.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享给质押的比例 (0% - 100%):.
        /// </summary>
        internal static string Ratio_to_share_to_staking__0____100___ {
            get {
                return ResourceManager.GetString("Ratio to share to staking (0% - 100%):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除质押…….
        /// </summary>
        internal static string Remove_staking___ {
            get {
                return ResourceManager.GetString("Remove staking...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 席位数.
        /// </summary>
        internal static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 席位数量.
        /// </summary>
        internal static string Seats_number {
            get {
                return ResourceManager.GetString("Seats number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享比例.
        /// </summary>
        internal static string Share_Ratio {
            get {
                return ResourceManager.GetString("Share Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有质押账号.
        /// </summary>
        internal static string Staking_Accounts {
            get {
                return ResourceManager.GetString("Staking Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质押数额.
        /// </summary>
        internal static string Staking_Amount {
            get {
                return ResourceManager.GetString("Staking Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质押天数.
        /// </summary>
        internal static string Staking_Days {
            get {
                return ResourceManager.GetString("Staking Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质押给地址：.
        /// </summary>
        internal static string Staking_For_Address_ {
            get {
                return ResourceManager.GetString("Staking For Address:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质押已过期。现在可以安全移除质押。.
        /// </summary>
        internal static string Staking_has_expired__It_s_now_safe_to_unstake_ {
            get {
                return ResourceManager.GetString("Staking has expired. It\'s now safe to unstake.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质押到账号.
        /// </summary>
        internal static string Staking_to_Account {
            get {
                return ResourceManager.GetString("Staking to Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质押在 {0} 小时后过期。.
        /// </summary>
        internal static string Staking_will_expire_in__0_N2__Hours_ {
            get {
                return ResourceManager.GetString("Staking will expire in {0:N2} Hours.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        internal static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功。更新中…….
        /// </summary>
        internal static string Success__Refreshing___ {
            get {
                return ResourceManager.GetString("Success. Refreshing...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖励总额.
        /// </summary>
        internal static string Total_Reward {
            get {
                return ResourceManager.GetString("Total Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型：.
        /// </summary>
        internal static string Type_ {
            get {
                return ResourceManager.GetString("Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除质押.
        /// </summary>
        internal static string Unstaking {
            get {
                return ResourceManager.GetString("Unstaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在承诺的质押期间移除质押会被收取 0.8% 的罚金。你确认要这么做吗？.
        /// </summary>
        internal static string Unstaking_within_the_promised_staking_period_will_pay_0_8__panalise_fee__Are_you_sure_you_want_to_confirm_ {
            get {
                return ResourceManager.GetString("Unstaking within the promised staking period will pay 0.8% panalise fee. Are you " +
                        "sure you want to confirm?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收益.
        /// </summary>
        internal static string Yield {
            get {
                return ResourceManager.GetString("Yield", resourceCulture);
            }
        }
    }
}
